dataset: INSTANCE
protocol: controlled_p_arrival_position
positions: [750, 1500, 2000, 2750, 2900]
validation_selected:
  PhaseNet:
    750:  {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    1500: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2000: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2750: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2900: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
  EQTransformer:
    750:  {single: {type: continue, probability: 0.08, trigger_length: 40}, multi: {type: max, probability: 0.02}}
    1500: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2000: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2750: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.05}}
    2900: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
  ViT:
    750:  {single: {type: max, probability: 0.01}, multi: {type: continue, probability: 0.01, trigger_length: 25}}
    1500: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2000: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2750: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
    2900: {single: {type: max, probability: 0.01}, multi: {type: max, probability: 0.01}}
